-- Users Data
INSERT INTO users (dni, username, password, name, last_name,  birth_date, email, type) VALUES ('0000000', 'admin','Administrador123', 'Administrador', 'Administrador', '1990-01-01', 'Administrador@gmail.com', 'Administrador');
INSERT INTO users (dni, username, password, name, last_name,  birth_date, email, type) VALUES ('5928025', 'rseveric', 'secret123', 'Richard', 'Severich', '1994-05-26', 'Richard.Severich@gmail.com', 'Administrador');
INSERT INTO users (dni, username, password, name, last_name,  birth_date, email, type) VALUES ('2365874', 'cadoyl', 'pass123', 'Cory', 'Luza', '1994-10-28', 'Cory.Luza@gmail.com', 'Administrador');
INSERT INTO users (dni, username, password, name, last_name,  birth_date, email, type) VALUES ('5123659', 'michamu', 'secret255', 'Michael', 'Jackson', '1984-02-15', 'Michael.Jackson@gmail.com', 'Administrador');
INSERT INTO users (dni, username, password, name, last_name,  birth_date, email, type) VALUES ('8475651', 'clarson', 'secret987', 'Charly', 'Garcia', '2000-12-13', 'Charly.Garcia@gmail.com', 'Administrador');
INSERT INTO users (dni, username, password, name, last_name,  birth_date, email, type) VALUES ('1236548', 'rmolina', 'secret654', 'Rodrigo', 'Molina', '1988-11-11', 'Rodrigo.Molina@gmail.com', 'Administrador');
INSERT INTO users (dni, username, password, name, last_name,  birth_date, email, type) VALUES ('0000001', 'client', 'client123', 'Client', 'Client', '1990-01-01', 'Client@gmail.com', 'Administrador');
INSERT INTO users (dni, username, password, name, last_name,  birth_date, email, type) VALUES ('8745698', 'rmorris', 'mela123', 'Rick Lorens', 'Morris', '1997-06-02', 'Rick.Morris@gmail.com', 'Administrador');
INSERT INTO users (dni, username, password, name, last_name,  birth_date, email, type) VALUES ('5236567', 'rharrys', 'kass889', 'Rick', 'Harrys', '1989-08-15', 'Rick.Harrys@gmail.com', 'Administrador');
INSERT INTO users (dni, username, password, name, last_name,  birth_date, email, type) VALUES ('7896321', 'aflores', 'mula777', 'Andrea', 'Flores', '1997-07-06', 'Andrea.Flores@gmail.com', 'Administrador');
INSERT INTO users (dni, username, password, name, last_name,  birth_date, email, type) VALUES ('5928354', 'lsimpson', 'cass222', 'Liza', 'Simpson', '1992-03-18', 'Liza.Simpson@gmail.com', 'Administrador');
INSERT INTO users (dni, username, password, name, last_name,  birth_date, email, type) VALUES ('2136545', 'iortega', 'upa4848', 'Iza', 'Ortega', '1995-05-27', 'Iza.Ortega@gmail.com', 'Administrador');
INSERT INTO users (dni, username, password, name, last_name,  birth_date, email, type) VALUES ('7812653', 'esyler', 'vela778', 'Emily', 'Syler', '1996-04-03', 'Emily.Syler@gmail.com', 'Administrador');
INSERT INTO users (dni, username,password, name, last_name,  birth_date, email, type) VALUES ('9814256', 'mbros', 'user555', 'Mario', 'Bros', '1999-08-08', 'Mario.Bros@gmail.com', 'Profesor');
INSERT INTO users (dni, username,password, name, last_name,  birth_date, email, type) VALUES ('6636666', 'mbros14', 'mela888', 'Mario', 'Bros', '1998-08-08', 'Mario.Bros@gmail.com', 'Administrador');
INSERT INTO users (dni, username,password, name, last_name,  birth_date, email, type) VALUES ('9825789', 'amoppu', 'reyleon', 'Ariel', 'Moppu', '1997-02-12', 'Ariel.Moppu@gmail.com', 'Administrador');
INSERT INTO users (dni, username, password, name, last_name,  birth_date, email, type) VALUES ('9985501', 'mreyes', 'pass555', 'Manfred', 'Reyes', '1985-12-25', 'Manfred.Reyes@gmail.com', 'Administrador');
INSERT INTO users (dni, username, password, name, last_name,  birth_date, email, type) VALUES ('9985502', 'icruz', 'mysecret', 'Igor', 'Cruz', '1987-08-28', 'Igor.Cruz@gmail.com', 'Administrador');
INSERT INTO users (dni, username,password, name, last_name,  birth_date, email, type) VALUES ('9985503', 'dvera', 'secret', 'Daniel', 'Vera', '1997-03-11', 'Daniel.Vera@gmail.com', 'Administrador');
INSERT INTO users (dni, username, password, name, last_name,  birth_date, email, type) VALUES ('9985504', 'krpuu', 'holamundo', 'Keyur', 'Rpuu', '1997-04-10', 'Keyur.Rpuu@gmail.com', 'Administrador');
INSERT INTO users (dni, username, password, name, last_name,  birth_date, email, type) VALUES ('9985556', 'sasel', 'secret548', 'Sasel', 'Landia', '1997-04-20', 'Sasel.Landia@gmail.com', 'Profersor');
INSERT INTO users (dni, username, password, name, last_name,  birth_date, email, type) VALUES ('4512477', 'hmene', 'secret55', 'Horacio', 'Meneces', '1985-06-20', 'Horacio.Mene@gmail.com', 'Profersor');
INSERT INTO users (dni, username, password, name, last_name,  birth_date, email, type) VALUES ('5854744', 'pparker', 'secret', 'Peater', 'Parker', '1989-06-08', 'Peater.Parker@gmail.com', 'Profersor');
INSERT INTO users (dni, username, password, name, last_name,  birth_date, email, type) VALUES ('5845477', 'chavo8', 'kiko45', 'Chavo', 'Del8', '1975-06-08', 'Chavo8@gmail.com', 'Profersor');
INSERT INTO users (dni, username, password, name, last_name,  birth_date, email, type) VALUES ('5845478', 'pjirafales', 'kiko45', 'Ruben', 'Jirafales','1971-06-08', 'Jirafales@gmail.com', 'Profersor');
